image: node:alpine

stages:
  - build
  - test
  - deploy staging
  - deploy production
  - production tests

cache: 
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

variables:
  STAGING_DOMAIN: pozi-staging.surge.sh
  PRODUCTION_DOMAIN: pozi.surge.sh

build website:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - yarn install
    - yarn global add gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public
  except:
    - schedules

test artifact:
  image: alpine
  cache: {}
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html
  except:
    - schedules

test website:
  stage: test
  script:
    - yarn install
    - yarn global add gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
  except:
    - schedules

deploy staging:
  stage: deploy staging
  cache: {}
  environment:
    name: staging
    url: http://$STAGING_DOMAIN 
  script:
    - yarn global add surge
    - surge --project ./public --domain $STAGING_DOMAIN
  except:
    - schedules

deploy production:
  stage: deploy production
  cache: {}
  environment:
    name: production
    url: http://$PRODUCTION_DOMAIN
  when: manual
  allow_failure: false
  script:
    - yarn global add surge
    - surge --project ./public --domain $PRODUCTION_DOMAIN
  except:
    - schedules

production tests:
  image: alpine
  cache: {}
  stage: production tests
  script:
    - apk add --no-cache curl
    - curl -s "https://$PRODUCTION_DOMAIN" | grep -q "Hi people"
    - curl -s "https://$PRODUCTION_DOMAIN" | grep -q "$CI_COMMIT_SHORT_SHA"
  except:
    - schedules

update cache:
  script:
    - yarn install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push
  only:
    - schedules