image: node

stages:
  - build
  - test
  - deploy
  - deployment tests
  - cache

cache: 
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

build website:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - yarn install
    - yarn global add gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHORT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public
  except:
    - schedules

test artifact:
  image: alpine
  cache: {}
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html
  except:
    - schedules

test website:
  stage: test
  script:
    - yarn install
    - yarn global add gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"
  except:
    - schedules

deploy to surge:
  stage: deploy
  cache: {}
  script:
    - yarn global add surge
    - surge --project ./public --domain pozi.surge.sh
  except:
    - schedules

test deployment:
  image: alpine
  cache: {}
  stage: deployment tests
  script:
    - apk add --no-cache curl
    - curl -s "https://pozi.surge.sh" | grep -q "Hi people"
    - curl -s "https://pozi.surge.sh" | grep -q "$CI_COMMIT_SHORT_SHA"
  except:
    - schedules

update cache:
  stage: cache
  script:
    - yarn install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: push
  only:
    - schedules