image: node

stages:
  - build
  - test
  - deploy

build website:
  stage: build
  script:
    - echo $CI_COMMIT_SHORT_SHA
    - yarn install
    - yarn global add gatsby-cli
    - gatsby build
    - sed -i "s/%%VERSION%%/$CI_COMMIT_SHA/" ./public/index.html
  artifacts:
    paths:
      - ./public

test artifact:
  image: alpine
  stage: test
  script:
    - grep -q "Gatsby" ./public/index.html

test website:
  stage: test
  script:
    - yarn install
    - yarn global add gatsby-cli
    - gatsby serve &
    - sleep 3
    - curl "http://localhost:9000" | tac | tac | grep -q "Gatsby"

deploy to surge:
  stage: deploy
  script:
    - yarn global add surge
    - surge --project ./public --domain pozi.surge.sh
